language: java
jdk:
  - oraclejdk8
dist: trusty
sudo: required
cache:
  directories:
    - .tmp/
    - ivy/
    - $HOME/.ivy2/

env:
  global:
    - _IVY_VERSION=2.5.0
    - PACKAGE_VERSION=0.7.$TRAVIS_BUILD_NUMBER

install:
  - . build/.bashrc

  # Apache Ivy
  - if [ ! -d ivy ]; then mkdir ivy; fi
  - if [ ! -f ivy/ivy.jar ]; then wget -nv -O ivy/ivy.jar https://repo1.maven.org/maven2/org/apache/ivy/ivy/$_IVY_VERSION/ivy-$_IVY_VERSION.jar; fi
  - $JAVA_HOME/bin/java -jar ivy/ivy.jar -retrieve "ivy/lib/[conf]/[artifact].[ext]"

script:
  - $ANT_HOME/bin/ant -noclasspath -nouserlib -noinput -lib "ivy/lib/test" -logger org.apache.tools.ant.listener.AnsiColorLogger -f build.xml release

deploy:
  provider: releases
  api_key:
    secure: wShPQnxchn5rc99eRCrGZ034/nhTixhTKNyz+QnP0v+FSlnA0bj/QhOtnaBkLDcagyE2662FKoLDPkghq4TWBjKpkFyTgaplCA3kFH473b8uNPCCa1WpJnDTpy5atkxK/E2V27E+TYGJSKz43+lw/7wNHnEmH+6boqudztwcvRHf5ibD5NRrZLuuz1hXCWNw97C2xMayTjawLRyV5/EgTF4TzetxLeulygn0K1gt8tCKx2jgC6i1qxuD8Ed7/y0ka4dDck5uC+XQfYr/rrsldE4eVhKorw9Z6pZz/UjQjFaF5g2NtwjhME5Pp7Drofetx+Mr5vrTJWSvpHSTOldijAymNGIlRORFYNKNfiuyD4RdeymtU7nvxkfMtxV6w0b9Q3D5L48ajUXRdCcF/TG/MyVjYgVf3oV2UMqi4E+NoWxCU3Vq/r0anNW0AijOtaoU6ygJcu8zthDypXJq/RbrmEqJsy/Sfr+VFCN0LJdTOkm8WBB5ni7ukfpA0lKiSeyNdokSjh/tFuHc/STdjWyyS4CUZ7b4Cefy3eq1pNXTJTvwVSrmM0UHoSC1qITJMegGNE2zY10F29hSXWnlC2g4gwZFQ2YZDQcfeM8ZjWsU+WxQ7GawfQzrAIhVJjauFX7cTCJoJYoytkAe69GwqcIpDk9uDyexRq6kqS6aFNI+Q5Q=
  file_glob: true
  file: tmp/out/bin/*
  skip_cleanup: true
  on:
    tags: true
